-- Web Push reminders.
--
-- A pg_cron job (see supabase/updates/*.sql) POSTs to <site>/api/push-tick every
-- minute with the cron secret. The endpoint calls push_due(secret), which
-- works out what each subscribed device should be told right now, and sends it.
-- Keys and the secret live in push_config, which is not exposed through the API.

CREATE TABLE IF NOT EXISTS public.push_config (
  id integer PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  cron_secret text NOT NULL DEFAULT replace(gen_random_uuid()::text || gen_random_uuid()::text, '-', ''),
  site_url text,
  vapid_public text,
  vapid_private text
);
ALTER TABLE public.push_config ENABLE ROW LEVEL SECURITY; -- no policies: API can't read it
INSERT INTO public.push_config (id) VALUES (1) ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS public.push_subscriptions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  endpoint text NOT NULL UNIQUE,
  p256dh text NOT NULL,
  auth text NOT NULL,
  timezone text NOT NULL DEFAULT 'UTC',
  test_requested boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.push_subscriptions TO authenticated;
GRANT ALL ON public.push_subscriptions TO service_role;
ALTER TABLE public.push_subscriptions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "own push_subscriptions" ON public.push_subscriptions;
CREATE POLICY "own push_subscriptions" ON public.push_subscriptions FOR ALL TO authenticated
  USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- What was already sent to which device, so every reminder goes out once.
CREATE TABLE IF NOT EXISTS public.push_log (
  subscription_id uuid NOT NULL REFERENCES public.push_subscriptions(id) ON DELETE CASCADE,
  key text NOT NULL,
  sent_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (subscription_id, key)
);
ALTER TABLE public.push_log ENABLE ROW LEVEL SECURITY; -- no policies

-- Public VAPID key for subscribing in the browser.
CREATE OR REPLACE FUNCTION public.push_public_key()
RETURNS text LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT vapid_public FROM push_config WHERE id = 1;
$$;
GRANT EXECUTE ON FUNCTION public.push_public_key() TO anon, authenticated;

CREATE OR REPLACE FUNCTION public.push_check_secret(p_secret text)
RETURNS void LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF p_secret IS NULL OR p_secret <> (SELECT cron_secret FROM push_config WHERE id = 1) THEN
    RAISE EXCEPTION 'invalid push secret' USING ERRCODE = '28000';
  END IF;
END; $$;

-- VAPID key pair for the sender (generated by the endpoint on first run).
CREATE OR REPLACE FUNCTION public.push_keys(p_secret text)
RETURNS TABLE (vapid_public text, vapid_private text)
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  PERFORM push_check_secret(p_secret);
  RETURN QUERY SELECT c.vapid_public, c.vapid_private FROM push_config c WHERE c.id = 1;
END; $$;

CREATE OR REPLACE FUNCTION public.push_set_keys(p_secret text, p_public text, p_private text)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  PERFORM push_check_secret(p_secret);
  UPDATE push_config SET vapid_public = p_public, vapid_private = p_private
  WHERE id = 1 AND vapid_public IS NULL;
END; $$;

CREATE OR REPLACE FUNCTION public.push_remove_subscription(p_secret text, p_endpoint text)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  PERFORM push_check_secret(p_secret);
  DELETE FROM push_subscriptions WHERE endpoint = p_endpoint;
END; $$;

-- Reminders due right now, one row per (device, notification). Marks them as sent.
--   * at the task's time (within 10 minutes)
--   * once more if it's still not done an hour later
--   * a summary of what's left at 09:00, 13:00, 18:00 and 21:00
-- Also creates today's routine instances, so routines remind even if the app
-- wasn't opened today. Times are evaluated in each device's timezone.
CREATE OR REPLACE FUNCTION public.push_due(p_secret text)
RETURNS TABLE (endpoint text, p256dh text, auth text, title text, body text, tag text)
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  s record;
  t record;
  local_now timestamp;
  today date;
  now_min integer;
  start_min integer;
  pending_count integer;
  pending_titles text;
BEGIN
  PERFORM push_check_secret(p_secret);
  DELETE FROM push_log WHERE sent_at < now() - interval '3 days';

  FOR s IN SELECT * FROM push_subscriptions LOOP
    local_now := now() AT TIME ZONE coalesce(nullif(s.timezone, ''), 'UTC');
    today := local_now::date;
    now_min := extract(hour FROM local_now)::int * 60 + extract(minute FROM local_now)::int;

    INSERT INTO tasks (user_id, title, scheduled_for, occurrence_date, scheduled_time, routine_id, sort_order, scope)
    SELECT r.user_id, r.title, today, today,
           CASE WHEN r.time_of_day ~ '^\d{1,2}:\d{2}(:\d{2})?$' THEN r.time_of_day::time END,
           r.id, r.sort_order, 'day'
    FROM routines r
    WHERE r.user_id = s.user_id AND r.active
      AND r.starts_on <= today AND (r.ends_on IS NULL OR r.ends_on >= today)
      AND extract(dow FROM today)::smallint = ANY (r.weekdays)
    ON CONFLICT (routine_id, occurrence_date) DO NOTHING;

    IF s.test_requested THEN
      UPDATE push_subscriptions SET test_requested = false WHERE id = s.id;
      endpoint := s.endpoint; p256dh := s.p256dh; auth := s.auth;
      title := 'Lumen'; body := 'Уведомления работают 🎉'; tag := 'lumen-test';
      RETURN NEXT;
    END IF;

    FOR t IN
      SELECT tk.id, tk.title, tk.scheduled_time FROM tasks tk
      WHERE tk.user_id = s.user_id AND tk.scheduled_for = today
        AND NOT tk.completed AND NOT tk.skipped AND tk.scheduled_time IS NOT NULL
    LOOP
      start_min := extract(hour FROM t.scheduled_time)::int * 60 + extract(minute FROM t.scheduled_time)::int;
      IF now_min BETWEEN start_min AND start_min + 10 THEN
        INSERT INTO push_log (subscription_id, key) VALUES (s.id, 'task:' || t.id || ':' || today)
        ON CONFLICT DO NOTHING;
        IF FOUND THEN
          endpoint := s.endpoint; p256dh := s.p256dh; auth := s.auth;
          title := 'Lumen · пора'; body := to_char(t.scheduled_time, 'HH24:MI') || ' · ' || t.title;
          tag := 'lumen-task-' || t.id;
          RETURN NEXT;
        END IF;
      ELSIF now_min >= start_min + 60 THEN
        INSERT INTO push_log (subscription_id, key) VALUES (s.id, 'late:' || t.id || ':' || today)
        ON CONFLICT DO NOTHING;
        IF FOUND THEN
          endpoint := s.endpoint; p256dh := s.p256dh; auth := s.auth;
          title := 'Lumen · ещё не сделано';
          body := t.title || ' — было на ' || to_char(t.scheduled_time, 'HH24:MI');
          tag := 'lumen-late-' || t.id;
          RETURN NEXT;
        END IF;
      END IF;
    END LOOP;

    IF extract(hour FROM local_now)::int IN (9, 13, 18, 21) THEN
      SELECT count(*) INTO pending_count FROM tasks tk
      WHERE tk.user_id = s.user_id AND tk.scheduled_for = today AND NOT tk.completed AND NOT tk.skipped;
      IF pending_count > 0 THEN
        INSERT INTO push_log (subscription_id, key)
        VALUES (s.id, 'summary:' || today || ':' || extract(hour FROM local_now)::int)
        ON CONFLICT DO NOTHING;
        IF FOUND THEN
          SELECT string_agg(y.title, ', ') INTO pending_titles FROM (
            SELECT tk.title FROM tasks tk
            WHERE tk.user_id = s.user_id AND tk.scheduled_for = today AND NOT tk.completed AND NOT tk.skipped
            ORDER BY tk.scheduled_time NULLS LAST, tk.sort_order LIMIT 3
          ) y;
          endpoint := s.endpoint; p256dh := s.p256dh; auth := s.auth;
          title := 'Lumen · осталось ' || pending_count;
          body := pending_titles || CASE WHEN pending_count > 3 THEN ' и ещё ' || (pending_count - 3) ELSE '' END;
          tag := 'lumen-summary';
          RETURN NEXT;
        END IF;
      END IF;
    END IF;
  END LOOP;
END; $$;

-- Only the endpoint (holding the secret) may call these; the secret is checked inside.
REVOKE ALL ON FUNCTION public.push_check_secret(text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.push_keys(text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.push_set_keys(text, text, text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.push_remove_subscription(text, text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.push_due(text) TO anon, authenticated;
